import type { Metadata } from "next";
import { UIProvider } from "@/components/Provider";
import "./globals.css";
import { Navgation } from "@/components/Navgation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="dark text-foreground bg-background">
        <UIProvider>
          <Navgation />
          {children}
        </UIProvider>
      </body>
    </html>
  );
}
